# Generated by Django 4.2.7 on 2023-11-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_user_is_verified_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
